<a href="https://colab.research.google.com/github/Sayanik-tech/Deep_Learning-ANN/blob/main/Combined_Cycle_Power_Plant_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [81]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [82]:
dataset = pd.read_excel('CCPP.xlsx')
dataset.head()

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [83]:
x = dataset.iloc[: , :-1].values
y = dataset.iloc[: , -1].values
print(x)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


In [84]:
dataset.rename(columns={'AT':'Temperature','V':'Vaccum','AP':'Pressure','RH':'Humidity','PE':'Output_Energy'},inplace = True)
dataset.head()

Temperature  Vaccum  Pressure  Humidity  Output_Energy
0        14.96   41.76   1024.07     73.17         463.26
1        25.18   62.96   1020.04     59.08         444.37
2         5.11   39.40   1012.16     92.14         488.56
3        20.86   57.32   1010.24     76.64         446.48
4        10.82   37.50   1009.23     96.62         473.90

In [85]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x , y , test_size = 0.2 , random_state = 101)

In [86]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
print(x_train)

[[ 0.59  0.8  -0.47  0.78]
 [-0.22 -0.92 -0.74 -0.57]
 [-1.2  -1.37  1.57  0.49]
 ...
 [-1.08 -1.31  0.18 -0.25]
 [-1.71 -1.16  1.1  -0.07]
 [-1.49 -1.06  0.35  1.27]]


**Initializing ANN and adding Layers**

In [87]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
ann = Sequential()

In [88]:
ann.add(Dense(8,activation = 'relu',kernel_initializer='he_uniform'))

In [89]:
ann.add(Dense(4,activation = 'sigmoid'))

In [90]:
ann.add(Dense(2,activation = 'relu',kernel_initializer='he_uniform'))

**Adding output Layer**

In [91]:
ann.add(Dense(units = 1))   ## For classification problems it is better to use 'Sigmoid' or 'Softmax' activation function but for regression problems it is better to use No activation functions

**Training The ANN Model(Compilation,Training**)

In [92]:
ann.compile(optimizer='adam',loss='mean_squared_error')

In [93]:
ann.fit(x_train, y_train, batch_size = 32, epochs=100)

Epoch 1/100
240/240 [==============================] - 1s 3ms/step - loss: 206778.8281
Epoch 2/100
240/240 [==============================] - 1s 3ms/step - loss: 205263.3750
Epoch 3/100
240/240 [==============================] - 1s 3ms/step - loss: 202870.9531
Epoch 4/100
240/240 [==============================] - 1s 3ms/step - loss: 199962.2188
Epoch 5/100
240/240 [==============================] - 1s 3ms/step - loss: 196513.8281
Epoch 6/100
240/240 [==============================] - 1s 3ms/step - loss: 192559.2031
Epoch 7/100
240/240 [==============================] - 1s 3ms/step - loss: 188142.8281
Epoch 8/100
240/240 [==============================] - 1s 3ms/step - loss: 183313.5781
Epoch 9/100
240/240 [==============================] - 1s 3ms/step - loss: 178117.8438
Epoch 10/100
240/240 [==============================] - 1s 3ms/step - loss: 172600.8125
Epoch 11/100
240/240 [==============================] - 1s 3ms/step - loss: 166805.1875
Epoch 12/100
240/240 [===================

**Predicting the reults of Test Set**

In [94]:
y_pred = ann.predict(x_test)
np.set_printoptions(precision = 2)
np.concatenate((y_test.reshape(len(y_test),1) , y_pred.reshape(len(y_pred),1)),1)

array([[466.52, 470.36],
       [461.73, 462.22],
       [450.73, 453.32],
       ...,
       [458.07, 449.61],
       [432.66, 436.41],
       [430.55, 433.38]])

In [95]:
ann.predict(sc.transform([[18,58,1010,76]]))

array([[453.78]], dtype=float32)